spring:
  datasource:
    url: jdbc:h2:mem:dentist_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


dentist-app:
  server-url: "http://dentistapp.com"
  auth-config:
    access-token:
      lifetime: 5m
    refresh-token:
      lifetime: 8h
    purging-refresh-tokens-cron: "* * 0/6 * * *"

springdoc:
  swagger-ui:
    path: /swagger.html